#!/usr/bin/env bash

PACKAGE=ctags
[ -z $VERSION ] && VERSION='5.8'

set_variables
URL=http://garr.dl.sourceforge.net/project/ctags/ctags/$VERSION/$STOW.tar.gz

if [ ! -z $DRIP_INSTALL ]; then
  pushd $SRC_PATH
  curl -O $URL
  tar xvf $STOW.tar.gz
  cd $STOW
  ./configure \
    --prefix=$PREFIX \
    --enable-macro-patterns \
    --with-readlib
  make install
  popd
fi
