#!/usr/bin/env bash

PACKAGE=example
VERSION=1.3.3
DEBUG=true

echo "Package: $PACKAGE"
echo "Version: $VERSION"

if [ ! -z $DRIP_INSTALL ]; then
  echo "=> Install"
  exit
fi

if [ ! -z $DRIP_UNINSTALL ]; then
  echo "=> Uninstall"
  exit
fi

if [ ! -z $DRIP_INFO ]; then
  echo "=> Info"
  exit
fi
