#!/usr/bin/env bash

PACKAGE=sphinx
VERSION=2.0.4

set_variables

if [ ! -z $DRIP_INSTALL ]; then
  pushd $SRC_PATH
  curl -O http://sphinxsearch.com/files/$STOW-release.tar.gz
  tar xzf $STOW-release.tar.gz
  cd $STOW-release
  ./configure --prefix=$PREFIX
  make && make install
  popd
fi
