#!/usr/bin/env bash

set -e

if [ -z $(which cram) ]; then
  echo "Cram not installed. Install with \`pip install cram'."
  echo "More info about cram at https://bitheap.org/cram/"
  exit 1
fi

cram -vi test/*.t
