#!/usr/bin/env bash

_INSTALL=true

source drip-base
source drip-validator

# If package is already compiled under the $STOW_PATH folder we can
# re-use it, otherwise perform the typical operations provided by the
# definition.

if [ -d $STOW_PATH/$1 ]; then
  drip link $1
else
  source $STOW_DEFINITIONS_PATH/$1
  stow_link_one
fi
