#!/usr/bin/env bash

# If no drip provided, then exit.
if [ ! $1 ]; then
  echo "No drip provided. Get a list with \`drip list'."
  exit 1
fi

# If drip provided verify it exists on the `drips_path`.
if [ $1 ]; then
  if [ ! -f $DRIPS_PATH/$1 ]; then
    message="Drip doesn't exist."
    ls -1 $DRIPS_PATH/$1* > /dev/null 2>&1

    if [ $? = "0" ]; then
      echo "$message Suggested packages:"
      { for drip in "${DRIPS_PATH}/$1"*; do
        echo "=> ${drip##*/}"
      done } | sort
      exit
    else
      echo $message
    fi

    exit
  fi
fi
