#!/usr/bin/env bash

set -e
[ ! -z $DEBUG ] && set -x

if (( UID == 0 )) ; then
  LOCAL_PATH=/usr/local
else
  LOCAL_PATH=$HOME/.packages
fi

mkdir -p $LOCAL_PATH/{stow,src}
mkdir -p $LOCAL_PATH/{bin,etc,include,lib,libexec,var,info}
mkdir -p $LOCAL_PATH/share/man/{man1,man2,man3,man4,man5,man6,man7,man8,man9,mann}
mkdir -p $LOCAL_PATH/Library
