#!/usr/bin/env bash

_UNINSTALL=true

source drip-base
source drip-validator
source $STOW_DEFINITIONS_PATH/$1

stow_remove() {
  echo "Removing package files ..."
  rm -rf $STOW_PATH/$STOW
}

stow_unlink
stow_remove
