#!/usr/bin/env bash

# Display colorized information output
function cinfo() {
  COLOR='\033[01;33m' # bold yellow
  RESET='\033[00;00m' # normal white
  MESSAGE=${@:-"${RESET}Error: No message passed"}
  echo -e "${COLOR}${MESSAGE}${RESET}"
}

# Display colorized warning output
function cwarn() {
  COLOR='\033[01;31m' # bold red
  RESET='\033[00;00m' # normal white
  MESSAGE=${@:-"${RESET}Error: No message passed"}
  echo -e "${COLOR}${MESSAGE}${RESET}"
}

set_variables() {
  STOW=$PACKAGE-$VERSION
  PREFIX=$STOW_PATH/$STOW
}

verify_installed() {
  if [ ! -d $STOW_PATH/$1 ]; then
    echo "Error: ${1} is not installed."
  fi
}

# TODO: Before linking detect similar formula linked!
stow_link() {
  if [ -f $STOW_PATH/.stow_${1} ]; then
    echo "${1} already linked."
  else
    echo "${1} linked."
    stow -d $STOW_PATH $1
    touch $STOW_PATH/.stow_${1}
  fi
}

stow_unlink() {
  if [ ! -f $STOW_PATH/.stow_${1} ]; then
    echo "${1} not linked."
  else
    echo "${1} unlinked."
    stow -D -d $STOW_PATH ${1}
    rm $STOW_PATH/.stow_${1}
  fi
}

stow_link_one() {
  verify_installed $STOW
  stow_link $STOW
}

stow_unlink_one() {
  verify_installed $STOW
  stow_unlink $STOW
}

stow_link_all() {
  for item in $STOW_PATH/*; do
    stow_link ${item##*/}
  done
}

stow_unlink_all() {
  for item in $STOW_PATH/*; do
    item=${item##*/}
    if [ $item = 'stow-1.3.3' ]; then
      echo "${item} not unlinked."
    else
      stow_unlink $item
    fi
  done
}

_install() {
  [ ! -z $_INSTALL ]
}

_uninstall() {
  [ ! -z $_UNINSTALL ]
}

_info() {
  [ ! -z $_INFO ]
}

_link() {
  [ ! -z $_LINK ]
}

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

set_options() {
  all=""
  if [ "$1" = "--all" ]; then
    all=1
  fi
}
