#!/usr/bin/env bash

source drip-requirements
source drip-base

set_options $*

# drip unlink --all
if [ -n "$all" ]; then
  for stow in $STOW_PATH/*; do
    current_stow=${stow##*/}
    if [ ! $current_stow = 'stow-1.3.3' ]; then
      $STOW_BINARY -v -D -d $STOW_PATH $current_stow
    else
      special_definition='stow-1.3.3'
    fi
  done

  # Last package we want to remove is `stow` otherwise we would be
  # unable to run `stow` to unlink packages.
  if [ -n "$special_definition" ]; then
    $STOW_BINARY -v -D -d $STOW_PATH $special_definition
  fi
  exit
fi

# drip unlink <package>
source drip-validator
source $STOW_DEFINITIONS_PATH/$1
stow_unlink
