#!/usr/bin/env bash

source drip-requirements
source drip-base
source drip-helper

set_options $*

# drip unlink --all
if [ -n "$all" ]; then
  for stow in $STOW_PATH/*; do
    current_stow=${stow##*/}
    if [ ! $current_stow = 'stow-1.3.3' ]; then
      stow -v -D -d $STOW_PATH $current_stow
    else
      special_drip='stow-1.3.3'
    fi
  done

  if [ -n "$special_drip" ]; then
    stow -v -D -d $STOW_PATH $special_drip
  fi
  exit
fi

# drip unlink <drip-version>
source drip-validator
source $DRIPS_PATH/$1
stow_unlink
