#!/usr/bin/env bash

# If no package provided, then exit with an error.
if [ ! $1 ]; then
  echo "This command requires a definition argument."
  exit 1
fi

# If package provided verify it exists on the `definitions` otherwise
# suggest a package with similar name.
#
# Exit command with an error because we could not perform the action
# the user wanted.
if [ ! -f $STOW_DEFINITIONS_PATH/$1 ]; then
  message="No available definition for $1."

  if [ -e `echo $STOW_DEFINITIONS_PATH/$1* | cut -d " " -f1` ]; then
    echo "$message Suggested packages:"
    PACKAGES=$(ls ${STOW_DEFINITIONS_PATH}/${1}*)
    for item in $PACKAGES; do
      echo "=> ${item##*/}"
    done
  else
    echo $message
  fi

  exit 1
fi
