#!/usr/bin/env bash

require_darwin() {
  if [ ! $(uname) == 'Darwin' ]; then
    echo "This \`definition' is only valid for Darwin."
    exit 1
  fi
}

require_hg() {
  if [ ! $(which hg) ]; then
    echo "Dripper needs \`hg' installed on the system."
    exit 1
  fi
}

# TODO: `drip install git` should detect latest version.
require_git() {
  if [ ! $(which git) ]; then
    echo "Dripper needs \`git' installed on the system."
    echo ""
    echo "    drip install git-1.7.10"
    echo ""
    exit 1
  fi
}

# TODO: `drip install stow` should detect latest version.
require_stow() {
  if [ ! $1 = 'stow-1.3.3' ] && [ ! $(which stow) ]; then
    echo "Dripper needs \`stow' installed on the system."
    echo ""
    echo "    drip install stow-1.3.3"
    echo ""
    exit 1
  fi

  if [ -n "$DRIPPER_DEBUG" ]; then
    echo "Skip install of stow because we are in debug mode."
    exit 1
  fi
}

require_stow $1
