#!/usr/bin/env bash

source drip-base

require_git

cd $DRIPPER_ROOT

if [ ! -d .git ]; then
  git init
  git config core.autocrlf false
  git remote add origin $DRIPPER_REPOSITORY
  git fetch origin
  git reset --hard origin/master
else
  git pull --rebase origin refs/heads/master:refs/remotes/origin/master
  git checkout master
fi
