#!/usr/bin/env bash

source drip-base

# Verify provided folder exists before doing anything, if it does not
# exist exit.
if [ ! -d $STOW_DEFINITIONS_PATH ]; then
  echo "Provided STOW_DEFINITIONS_PATH does not exist."
  exit 1
fi

if [ $1 ]; then
  PACKAGES=$(ls ${STOW_DEFINITIONS_PATH}/*$1*)
else
  PACKAGES=$(ls ${STOW_DEFINITIONS_PATH})
fi

list_definitions() {
  for item in $PACKAGES; do
    current_item=${item##*/}
    if [ -d ${STOW_PATH}/${current_item} ]; then
      echo "${current_item} (Installed)"
    else
      echo "${current_item}"
    fi
  done
}

if [ -n "${PACKAGES}" ]; then
  list_definitions
else
  echo "No definitions found."
  exit 1
fi
