#!/usr/bin/env bash

echo "usage: drip <command> [<args>]

The most commonly used drip commands are:

   list       List available drips
   install    Install a drip
   uninstall  Uninstall a drip
   update     Update drip repository
   show       Show a drip
   package    Build a package and install (Pending)
   info       Show package information
   link       Link package
   unlink     Unlink package
   cleanup    Remove all sources.

See 'drip help <command>' for information on a specific command."
