#!/usr/bin/env bash

source drip-base

REPOSITORY=git://github.com/fesplugas/dripper.git

cd $LOCAL_PATH

if [ ! -d .git ]; then
  git init
  git config core.autocrlf false
  git remote add origin $REPOSITORY
  git fetch origin
  git reset --hard origin/master
else
  git checkout -q master
fi
