#!/usr/bin/env bash

_LINK=true

source drip-requirements
source drip-base

set_options $*

# drip link --all
if [ -n "$all" ]; then
  for item in $STOW_PATH/*; do
    current_stow=${item##*/}
    stow -v -d $STOW_PATH $current_stow
    touch $STOW_PATH/.stow_$current_stow
  done

  exit
fi

# drip link <packages>
source drip-validator
source $STOW_DEFINITIONS_PATH/$1
stow_link
