#!/usr/bin/env bash

source drip-base

if [ $1 ]; then
  PACKAGES=$(ls ${STOW_DEFINITIONS_PATH}/*$1*)
else
  PACKAGES=$(ls ${STOW_DEFINITIONS_PATH})
fi

list_definitions() {
  for item in ${PACKAGES}; do
    echo "${item##*/}"
  done
}

if [ -n "${PACKAGES}" ]; then
  list_definitions
else
  echo "No definitions found."
  exit 1
fi
