#!/usr/bin/env bash

source ./libexec/drip-base
source ./libexec/drip-helper

bin_path="$(abs_dirname "$0")"
libexec_path="${bin_path}/../libexec"
export PATH="${libexec_path}:${bin_path}:${PATH}"

command="$1"
command_path="$(command -v "drip-$command" || true)"

case "$command" in
"" | "-h" | "--help" )
  echo -e "$(drip-help)" >&2
  ;;
* )
  if [ -z "$command_path" ]; then
    echo "drip: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
