#!/usr/bin/env bash

require_darwin() {
  if (( ! uname == 'Darwin' )) ; then
    echo "Drip no only valid for Darwin."
    exit
  fi
}

require_hg() {
  if [ ! $(which hg) ]; then
    echo "Dripper needs \`hg' installed on the system."
    exit
  fi
}

require_git() {
  if [ ! $(which git) ]; then
    echo "Dripper needs \`git' installed on the system."
    exit
  fi
}

require_stow() {
  if [ ! $1 = 'stow-1.3.3' ] && [ ! $(which stow) ]; then
    echo "Dripper needs \`stow' installed on the system:"
    echo ""
    echo "    drip install stow-1.3.3"
    echo ""
    exit
  fi
}
