#!/usr/bin/env bash

source stow-requirements
source stow-base
source stow-helper

set_options $*

# stow unlink --all
if [ -n "$all" ]; then
  for stow in $STOW_PATH/*; do
    current_stow=${stow##*/}
    if [ ! $current_stow = 'stow-1.3.3' ]; then
      $STOW_BINARY -v -D -d $STOW_PATH $current_stow
    else
      special_drip='stow-1.3.3'
    fi
  done

  if [ -n "$special_drip" ]; then
    $STOW_BINARY -v -D -d $STOW_PATH $special_drip
  fi
  exit
fi

# stow unlink <package>
source stow-validator
source $DRIPS_PATH/$1
stow_unlink
