#!/usr/bin/env bash

_INSTALL=true

source stow-requirements
source stow-base
source stow-helper
source stow-validator

# If package is already compiled under the $STOW_PATH folder we can
# re-use it, otherwise perform the typical operations provided by the
# drip.

if [ -d $STOW_PATH/$1 ]; then
  stow link $1
else
  source $STOW_DEFINITIONS_PATH/$1
  stow_link
fi
