#!/usr/bin/env bash

_LINK=true

source stow-requirements
source stow-helper
source stow-base

set_options $*

# stow link --all
if [ -n "$all" ]; then
  for item in $STOW_PATH/*; do
    current_stow=${item##*/}
    $STOW_BINARY -v -d $STOW_PATH $current_stow
  done

  exit
fi

# stow link <packages>
source stow-validator
source $DRIPS_PATH/$1
stow_link
