#!/usr/bin/env bash

require_darwin() {
  if [ ! $(uname) == 'Darwin' ]; then
    echo "This \`definition' is only valid for Darwin."
    exit
  fi
}

require_hg() {
  if [ ! $(which hg) ]; then
    echo "Stow manager needs \`hg' installed on the system."
    exit
  fi
}

require_git() {
  if [ ! $(which git) ]; then
    echo "Stow manager needs \`git' installed on the system."
    exit
  fi
}

require_stow() {
  if [ ! $1 = 'stow-1.3.3' ] && [ ! $(which $STOW_BINARY) ]; then
    echo "Stow manager needs \`stow' installed on the system:"
    echo ""
    echo "    stow install stow-1.3.3"
    echo ""
    exit
  fi
}

STOW_BINARY='stow_local'
require_stow $1
