#!/usr/bin/env bash

source stow-base

PACKAGES=$(ls ${STOW_DEFINITIONS_PATH})

list_definitions() {
  for item in ${PACKAGES}; do
    echo "${item##*/}"
  done
}

if [ -n "${PACKAGES}" ]; then
  list_definitions
else
  echo "No definitions found."
  exit 1
fi
