#!/usr/bin/env bash

source stow-requirements
source stow-base

require_git

cd $LOCAL_PATH

if [ ! -d .git ]; then
  git init
  git config core.autocrlf false
  git remote add origin $REPOSITORY
  git fetch origin
  git reset --hard origin/master
else
  git pull --rebase origin refs/heads/master:refs/remotes/origin/master
  git checkout master
fi
