#!/usr/bin/env bash

# If no package provided, then exit.
if [ ! $1 ]; then
  echo "No package provided. Get a list with \`stow list'."
  exit 1
fi

# If package provided verify it exists on the `definitions` folder.
if [ $1 ]; then
  if [ ! -f $STOW_DEFINITIONS_PATH/$1 ]; then
    message="Drip doesn't exist."

    if [ -e `echo $STOW_DEFINITIONS_PATH/$1* | cut -d " " -f1` ]; then
      echo "$message Suggested packages:"
      { for item in "${STOW_DEFINITIONS_PATH}/$1"*; do
        echo "=> ${item##*/}"
      done } | sort
      exit
    else
      echo $message
    fi

    exit
  fi
fi
