#!/usr/bin/env bash

# Display colorized information output
function cinfo() {
  COLOR='\033[01;33m' # bold yellow
  RESET='\033[00;00m' # normal white
  MESSAGE=${@:-"${RESET}Error: No message passed"}
  echo -e "${COLOR}${MESSAGE}${RESET}"
}

# Display colorized warning output
function cwarn() {
  COLOR='\033[01;31m' # bold red
  RESET='\033[00;00m' # normal white
  MESSAGE=${@:-"${RESET}Error: No message passed"}
  echo -e "${COLOR}${MESSAGE}${RESET}"
}

set_variables() {
  STOW=$PACKAGE-$VERSION
  PREFIX=$STOW_PATH/$STOW
}

stow_link() {
  if [ -f $STOW_PATH/.${STOW} ]; then
    echo "$STOW already linked."
    exit 1
  fi

  if [ -d $STOW_PATH/$STOW ]; then
    $STOW_BINARY -v -d $STOW_PATH $STOW
    touch $STOW_PATH/.${STOW}
  else
    echo "Error: $STOW is not installed."
    exit 1
  fi
}

stow_unlink() {
  if [ ! -f $STOW_PATH/.${STOW} ]; then
    echo "$STOW not linked."
    exit 1
  fi

  if [ -d $STOW_PATH/$STOW ]; then
    $STOW_BINARY -v -D -d $STOW_PATH $STOW
    rm $STOW_PATH/.${STOW}
  else
    echo "Error: $STOW is not installed."
    exit 1
  fi
}

stow_remove() {
  echo "Removing package files ..."
  rm -rf $STOW_PATH/$STOW
}

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

set_options() {
  all=""
  if [ "$1" = "--all" ]; then
    all=1
  fi
}
