#!/usr/bin/env bash

source stow-helper

if [ $(id -u) = "0" ]; then
  LOCAL_PATH=/usr/local
else
  LOCAL_PATH=$HOME/.packages
fi

CMD='stow'

SRC_PATH=$LOCAL_PATH/src
STOW_PATH=$LOCAL_PATH/stow

mkdir -p $SRC_PATH
mkdir -p $STOW_PATH

mkdir -p $LOCAL_PATH/{bin,include,lib,libexec,var,info}
mkdir -p $LOCAL_PATH/etc/bash_completion.d
mkdir -p $LOCAL_PATH/Library

# Man files can be in two different locations:
mkdir -p $LOCAL_PATH/man/{man1,man2,man3,man4,man5,man6,man7,man8,man9,mann}
mkdir -p $LOCAL_PATH/share/man/{man1,man2,man3,man4,man5,man6,man7,man8,man9,mann}

# Set STOW_PATH and STOW_DEFINITIONS_PATH!
STOW_PATH=$LOCAL_PATH/stow
STOW_DEFINITIONS_PATH="$(abs_dirname "$0")/../share/stow/definitions"

# Set repository location:
REPOSITORY=git://github.com/fesplugas/stow-manager.git
