#!/usr/bin/env bash

source stow-base

echo "usage: $CMD <command> [<args>]

The most commonly used $CMD commands are:

   search     Search a definition
   list       List installed packages
   install    Install a definition
   uninstall  Uninstall a definition
   update     Fetch new version and definitions
   show       Show a definition
   info       Show definition info
   link       Link package
   unlink     Unlink package
   cleanup    Remove all sources
   path       Show package path

See '$CMD help <command>' for information on a specific command."
