#!/usr/bin/env bash

_INFO=true

source stow-base
source stow-helper
source stow-validator

# Drip exists and is not installed, so go for it!
source $DRIPS_PATH/$1

# Drip should exit if information is shown."
echo "No info provided for $STOW."
