#!/usr/bin/env bash

source stow-base

list_stows() {
  { for item in "${STOW_PATH}/"*; do
      current_item=${item##*/}
      if [ -f ${STOW_PATH}/.${current_item} ]; then
        echo $current_item
      fi
    done
  } | sort
}

list_stows
