#!/usr/bin/env bash

echo "usage: stow <command> [<args>]

The most commonly used stow commands are:

   list       List available definitions
   install    Install a definition
   uninstall  Uninstall a definition
   update     Update stow repository
   show       Show a definition
   package    Build a package and install (Pending)
   info       Show definition info
   link       Link package
   unlink     Unlink package
   cleanup    Remove all sources.

See 'stow help <command>' for information on a specific command."
