#!/usr/bin/env bash

source stow-base

echo "usage: stow <command> [<args>]

The most commonly used stow commands are:

   search     Search a definition
   list       List installed packages
   install    Install a definition
   uninstall  Uninstall a definition
   update     Update stow repository
   show       Show a definition
   package    Build a package and install (Pending)
   info       Show definition info
   link       Link package
   unlink     Unlink package
   cleanup    Remove all sources
   path       Show package path

See 'stow help <command>' for information on a specific command."
