#!/usr/bin/env bash

_INFO=true

source stow-base
source stow-validator

# Definition exists and is not installed, so go for it!
source $STOW_DEFINITIONS_PATH/$1

# Stow manager should exit if information is shown."
echo "No info provided for $STOW."
